image: jmflaherty/medusajs-backend:latest
imagePullPolicy: IfNotPresent
resources:
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    memory: 256Mi
    cpu: 200m
storage:
  usePVC: false  # Default to emptyDir; override with values-local.yaml or values-prod.yaml
  size: 1Gi
  class: standard
ingress:
  className: nginx
  hostSuffix: "local.gd"
